import { cookies } from 'next/headers';
import { PropsWithChildren } from 'react';
import { AppProvider } from '@/domain/provider/app.provider';
import { LANGUAGE_COOKIE_NAME } from '@/shared/i18n/i18n.constants';
import { toSupportedLanguage } from '@/shared/i18n/utils/supported-language';
import { inter } from '@/shared/styles/fonts';
import { COLOR_SCHEME_COOKIE_NAME } from '@/shared/theme/theme.constants';
import { toSupportedColorScheme } from '@/shared/theme/utils/supported-color';
import { cn } from '@/shared/utils/cn';
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';
import type { Metadata } from 'next';

// 순서 중요!
import '@mantine/core/styles.css';
import '@shared/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  const language = toSupportedLanguage((await cookies()).get(LANGUAGE_COOKIE_NAME)?.value ?? '');
  const colorScheme = toSupportedColorScheme((await cookies()).get(COLOR_SCHEME_COOKIE_NAME)?.value ?? '');

  return (
    <html lang={language} {...mantineHtmlProps} data-color-scheme={colorScheme}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={cn('antialiased', inter.variable)}>
        <AppProvider colorScheme={colorScheme}>{children}</AppProvider>
      </body>
    </html>
  );
}
