import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import { PropsWithChildren } from 'react';
import { AppProvider } from '@/domain/provider/app.provider';
import { LANGUAGE_COOKIE_NAME } from '@/shared/i18n/i18n.constants';
import { getDefaultI18nLang } from '@/shared/i18n/utils/get-default-language';
import { cn } from '@/shared/utils/cn';
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';
import type { Metadata } from 'next';

// 순서 중요!
import '@mantine/core/styles.css';
import '@shared/styles/mantine.css';
import '@shared/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
});

export default async function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  const language = (await cookies()).get(LANGUAGE_COOKIE_NAME)?.value ?? getDefaultI18nLang();

  return (
    <html lang={language} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={cn('antialiased', pretendard.variable)}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
